menu = {

    "Full Tea":20,
    "Half Tea":10,
    "Espresso": 80,
    "Americano": 90,
    "Cold Coffee": 100,
    "Filter Coffee": 70,
    "Green Tea": 60,
    "Masala Chai": 50,
    "Lemon Tea": 50,
    "Hot Chocolate": 150,
    "Milkshake - Vanilla": 120,
    "Milkshake - Chocolate": 130,
    "Milkshake - Strawberry": 130,
    "Chocolate Muffin": 60,
    "Blueberry Muffin": 70,
    "Veg Sandwich": 100,
    "Cheese Sandwich": 110,
    "Paneer Sandwich": 120,
    "Club Sandwich": 140,
    "Veg Puff": 40,
    "Paneer Puff": 50,
    "French Fries": 90,
    "Peri Peri Fries": 100,
    "Garlic Bread": 80,
    "Cheesy Garlic Bread": 100,
    "Pasta - White Sauce": 150,
    "Pasta - Red Sauce": 140,
    "Pizza - Paneer Tikka": 230,
    "Veg Burger": 90,
    "Cheese Burger": 110,
    "Paneer Burger": 120,
    "Tandoori Burger": 130,
    "Oreo Shake": 140,
    "KitKat Shake": 140,
    "Bottled Water":20

}